_target_: ltvu.models.MATCH
backbone_name: 'dinov2-hf'
backbone_type: 'vitb14'
fix_backbone: True
backbone_precision: ${backbone_precision}
backbone_fp32_mm_precision: ${backbone_fp32_mm_precision}
num_layers_spatial_decoder: 1
resolution_transformer: 32
num_anchor_regions: 32
transformer_dropout: 0.0
base_sizes:
  - 16
  - 32
  - 64
  - 128
nhead_stx: 4

query_size: ${dataset.query_size[0]}
clip_size_fine: ${dataset.segment_size[0]}
clip_size_coarse: ${dataset.segment_size[0]}
clip_num_frames: ${dataset.num_frames}

positive_threshold: ${loss.positive_threshold}
logit_scale: ${loss.logit_scale}
weight_bbox_center: ${loss.weight_bbox_center}
weight_bbox_hw: ${loss.weight_bbox_hw}
weight_bbox_giou: ${loss.weight_bbox_giou}
weight_prob: ${loss.weight_prob}
weight_entropy: .1

enable_global_guidance: true
cls_repair_neighbor: true
enable_local_guidance: true

enable_temporal_shift_conv_summary: true
conv_summary_layers: 2
