_target_: project.models.vqloc.VQLoc
backbone_name: 'dinov2'
backbone_type: 'vitb14'
fix_backbone: True
num_transformer: 3
resolution_transformer: 8
resolution_anchor_feat: 16
pe_transformer: 'zero'
window_transformer: 5
positive_threshold: 0.2
positive_topk: 5

weight_bbox: 1.0
weight_bbox_center: 1.0
weight_bbox_hw: 1.0
weight_bbox_ratio: 1.0
weight_bbox_giou: 0.3
weight_prob: 100.0
