_target_: ltvu.models.VQLoC_guide
backbone_name: 'dinov2-hf'
backbone_type: 'vitb14'
fix_backbone: True
backbone_precision: ${backbone_precision}
backbone_fp32_mm_precision: ${backbone_fp32_mm_precision}
window_transformer: 5
resolution_transformer: 8
num_anchor_regions: 16
num_layers_st_transformer: 3
transformer_dropout: 0.0
enable_cls_token_score: True

query_size: ${dataset.query_size[0]}
clip_size_fine: ${dataset.segment_size[0]}
clip_size_coarse: ${dataset.segment_size[0]}
clip_num_frames: ${dataset.num_frames}

positive_threshold: ${loss.positive_threshold}
logit_scale: ${loss.logit_scale}
weight_bbox_center: ${loss.weight_bbox_center}
weight_bbox_hw: ${loss.weight_bbox_hw}
weight_bbox_giou: ${loss.weight_bbox_giou}
weight_prob: ${loss.weight_prob}
