augments:
  clip: True
  query: False
  clip_iter: -1  # iter to start clip augmentation
  prob_crop: 1.0
  crop_scale: 0.8
  crop_ratio_min: 0.8
  crop_ratio_max: 1.2
  # prob_affine: 1.0
  # affine_degree: 90
  # affine_scale_min: 0.9
  # affine_scale_max: 1.1
  # affine_shear_min: -15.0
  # affine_shear_max: 15.0
  # affine_translate: 0.2
  # https://github.com/hwjiang1510/VQLoC/blob/59460cd5ef605066fdd31a55afa6577d23ab0828/dataset/dataset_utils.py#L95
  prob_color: 1.0
  brightness: 0.4
  contrast: 0.4
  saturation: 0.3
  hue: 0
  prob_flip: 0.5
