defaults:
  - base
  - _self_


# required parameters
ckpt: ??? # 'outputs/batch/2024-09-15/124077/epoch=37-prob_acc=0.7626.ckpt'


# frequently overridden parameters
random_seed: 42
batch_size: 8
num_workers: 6
prefetch_factor: 2
base_lr: 0.0003
compile: false
backbone_precision: 'fp32'  # bf16 or fp32 or fp16
backbone_fp32_mm_precision: 'highest'  # medium or high or highest


# # runtime parameters
# jid: ${oc.env:SLURM_JOB_ID}
# job_type: ${job_type:}  # debug or batch
# YY: ${now:%Y}
# mm: ${now:%m}  # month
# dd: ${now:%d}  # day
# runtime_outdir: ${runtime_outdir:}


run_type: eval

trainer:
  logger: []
  inference_mode: true

dataset:
  padding_value: 'mean'  # zero or mean
  clips_dir: '/local_datasets/ego4d_data/v2/vq2d_frames/320ss'
  test_submit : False
