name: 'trek150'
###### torch #####
batch_size: ${batch_size}
num_workers: ${num_workers}
prefetch_factor: ${prefetch_factor}
pin_memory: True
persistent_workers: False  # No, our dataset is memory-bound
##### project-related #####
# clips or frames should be located like: ./{clip_uid}.mp4 or ./{clip_uid}/frame_{1+frame_idx:07d}.jpg
# for frames, frame_idxs should be 1-based
clips_dir: '/data/dataset/trek150/TREK-150'
flat_anns_dir: './data'
num_frames: 32
frame_interval: 1
segment_size: [448, 448]  # height, width
query_size: [448, 448]  # height, width
ope_benchmark : True
query_padding: False
query_square: True
padding_value: 'zero'  # zero or mean
num_train_samples: 13607
track_continual: True
track_last : False